# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "crates/infra_postgres/src/infrastructure/postgres/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "crates/infra_postgres/src/infrastructure/postgres/migrations"
